# Generated by Django 5.2.4 on 2025-07-29 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopresentation',
            name='ai_feedback_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='ai_feedback_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='ai_feedback_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='ai_feedback_status',
            field=models.CharField(choices=[('not_requested', 'Non demandée'), ('requested', 'Demandée'), ('processing', 'En cours'), ('completed', 'Terminée')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='videopresentation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
